/**
 * This code was generated by v0 by Vercel Labs.
 * @see https://v0.dev/t/x2IzBG2
 */


export function dashboard-analytics() {
return (<div className="flex flex-col space-y-6" >
  <div className="grid grid-cols-3 gap-6" >
    <Card >
      <CardHeader >
        <CardTitle >
          Monthly Active Users
        </CardTitle>
      </CardHeader>
      <CardContent >
        <svg
          className=" h-6 w-6 mb-4"
          fill="none"
          height="24"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="2"
          viewBox="0 0 24 24"
          width="24"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
          <circle cx="9" cy="7" r="4" />
          <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
          <path d="M16 3.13a4 4 0 0 1 0 7.75" />
        </svg>
        <p className="text-4xl" >
          10,000
        </p>
      </CardContent>
    </Card>
    <Card >
      <CardHeader >
        <CardTitle >
          Deployment Counts
        </CardTitle>
      </CardHeader>
      <CardContent >
        <svg
          className=" h-6 w-6 mb-4"
          fill="none"
          height="24"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="2"
          viewBox="0 0 24 24"
          width="24"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path d="M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242" />
          <path d="M12 12v9" />
          <path d="m16 16-4-4-4 4" />
        </svg>
        <p className="text-4xl" >
          1,200
        </p>
      </CardContent>
    </Card>
    <Card >
      <CardHeader >
        <CardTitle >
          Errors
        </CardTitle>
      </CardHeader>
      <CardContent >
        <svg
          className=" h-6 w-6 mb-4"
          fill="none"
          height="24"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="2"
          viewBox="0 0 24 24"
          width="24"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z" />
          <path d="M12 9v4" />
          <path d="M12 17h.01" />
        </svg>
        <p className="text-4xl" >
          50
        </p>
      </CardContent>
    </Card>
  </div>
  <div className="grid grid-cols-2 gap-6" >
    <Card >
      <CardHeader >
        <CardTitle >
          Monthly Active Users
        </CardTitle>
      </CardHeader>
      <CardContent >
        <div className="h-96 rounded-lg border border-zinc-200 border-dashed dark:border-zinc-800"  />
      </CardContent>
    </Card>
    <Card >
      <CardHeader >
        <CardTitle >
          Deployment Logs
        </CardTitle>
      </CardHeader>
      <CardContent >
        <div className="space-y-2" >
          <div className="flex items-center justify-between" >
            <p >
              Project 1
            </p>
            <p >
              12 deployments
            </p>
          </div>
          <div className="flex items-center justify-between" >
            <p >
              Project 2
            </p>
            <p >
              8 deployments
            </p>
          </div>
          <div className="flex items-center justify-between" >
            <p >
              Project 3
            </p>
            <p >
              20 deployments
            </p>
          </div>
        </div>
      </CardContent>
    </Card>
  </div>
  <div className="grid grid-cols-3 gap-6" >
    <Card >
      <CardHeader >
        <CardTitle >
          John Doe
        </CardTitle>
      </CardHeader>
      <CardContent >
        <div className="flex items-center space-x-4" >
          <Image
            alt="John Doe"
            className="rounded-full"
            height="40"
            src="/placeholder.jpg?height=40&width=40"
            width="40"
          />
          <div className="space-y-2" >
            <p >
              Deployments: 120
            </p>
            <div className="w-full h-2 bg-zinc-200 rounded-full" >
              <div '60%'="" className="h-full bg-zinc-900 rounded-full"  style={{}} width:="" }}="" />
            </div>
          </div>
        </div>
      </CardContent>
      <CardFooter >
        <Button className="w-full" >
          View Profile
        </Button>
      </CardFooter>
    </Card>
    <Card >
      <CardHeader >
        <CardTitle >
          Jane Doe
        </CardTitle>
      </CardHeader>
      <CardContent >
        <div className="flex items-center space-x-4" >
          <Image
            alt="Jane Doe"
            className="rounded-full"
            height="40"
            src="/placeholder.jpg?height=40&width=40"
            width="40"
          />
          <div className="space-y-2" >
            <p >
              Deployments: 80
            </p>
            <div className="w-full h-2 bg-zinc-200 rounded-full" >
              <div '40%'="" className="h-full bg-zinc-900 rounded-full"  style={{}} width:="" }}="" />
            </div>
          </div>
        </div>
      </CardContent>
      <CardFooter >
        <Button className="w-full" >
          View Profile
        </Button>
      </CardFooter>
    </Card>
    <Card >
      <CardHeader >
        <CardTitle >
          Project X
        </CardTitle>
      </CardHeader>
      <CardContent >
        <div className="flex items-center space-x-4" >
          <Image
            alt="Project X"
            className="rounded-full"
            height="40"
            src="/placeholder.jpg?height=40&width=40"
            width="40"
          />
          <div className="space-y-2" >
            <p >
              Deployments: 200
            </p>
            <div className="w-full h-2 bg-zinc-200 rounded-full" >
              <div '80%'="" className="h-full bg-zinc-900 rounded-full"  style={{}} width:="" }}="" />
            </div>
          </div>
        </div>
      </CardContent>
      <CardFooter >
        <Button className="w-full" >
          View Project
        </Button>
      </CardFooter>
    </Card>
  </div>
</div>)
}